In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.1.0'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
# Convert the array to a tensor
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])

In [9]:
arr2d = np.arange(0.0, 12.0).reshape(4,3)

In [10]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [12]:
# How to create a tensor without creating a reference to the original array!
my_tensor = torch.tensor(arr2d)

In [13]:
arr2d[0][0] = 99
arr2d

array([[99.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [14]:
my_tensor

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

In [16]:
# Reserve a "placeholder" block of memory
torch.empty(2,2)

tensor([[8.4078e-45, 0.0000e+00],
        [3.5759e-31, 1.4013e-45]])

In [17]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.rand(4,3)

tensor([[0.9104, 0.9696, 0.2404],
        [0.0714, 0.0357, 0.9671],
        [0.7371, 0.1046, 0.0540],
        [0.4496, 0.6407, 0.8448]])

In [21]:
torch.randint(1, 100, (3,3))

tensor([[50, 57, 87],
        [67,  1, 15],
        [11, 81, 94]])

In [22]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## TENSOR OPERATIONS

In [23]:
x = torch.arange(6).reshape(3,2)

In [24]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [25]:
x[1,1]

tensor(3)

In [26]:
x[:,1:]

tensor([[1],
        [3],
        [5]])